CREATE DATABASE IF NOT EXISTS mygxa DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mygxa;

CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  phone VARCHAR(20) NOT NULL UNIQUE,
  password VARCHAR(128) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (phone, password)
VALUES ('13800138000', 'Password123')
ON DUPLICATE KEY UPDATE phone = VALUES(phone);
